import google.generativeai as genai
import os, json

class GeminiCompiler:
    def __init__(self, key):
        genai.configure(api_key=key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')

    def synthesize(self, verdict, phys_score, conf_score, gen, results):
        prompt = f"""
        ROLE: Lead Forensic Structural Biologist for a Tier-1 Pharmaceutical Discovery Unit.
        AUDIT TARGET: Protein coordinates generated by {gen}.
        PHYSICAL INTEGRITY: {phys_score}% (Geometric Invariants)
        ML CONFIDENCE: {conf_score}% (pLDDT - Predicted Local Distance Difference Test)
        MEASUREMENTS: {json.dumps(results)}

        TASK: Write a 200-word authoritative biophysical synthesis for a Drug Discovery workflow.
        
        1. EXPLAIN THE MATH: Briefly explain that {conf_score}% pLDDT represents the model's prediction of its own local error. 
        2. ADDRESS THE DUALITY: Explain how a structure can be 100% physically valid (zero steric overlaps, canonical peptide registry) yet have low confidence (speculative tertiary packing).
        3. PHARMA IMPLICATION: 
           - If Phys=100 and Conf < 60: Warn that this design is 'chemically permissible but evidentially speculative'. High risk for aggregation or 'Intrinsically Disordered' behavior in the wet lab.
           - If VETO: Explain the 'Infinite Energy Gradients' caused by steric violations that make synthesis impossible.
        4. TERMINOLOGY: 'Pauli exclusion', 'Gibbs free energy', 'Cα-lDDT registry', 'tertiary packing', 'conformational entropy'.
        
        NO BULLET POINTS. Use one dense, professional paragraph.
        """
        try:
            response = self.model.generate_content(prompt)
            return response.text.replace('*', '').strip()
        except:
            return f"Audit confirms {phys_score}% Physical Integrity. ML Confidence ({conf_score}%) indicates speculative tertiary packing. Structure is permissible but lacks high-fidelity evidence."
